### ISSUE TITLE
Creating a resource with the same name after its deletion fails

### ISSUE THREAD

**Issue by machi1990** [openshift-online/maestro#101]
Reproducer:

1. Create the resource
```
ocm post /api/maestro/v1/resources << EOF
{
        "consumer_name": "cluster1", "name": "mambo-2",
        "version": 1,
        "manifest": {
          "apiVersion": "work.open-cluster-management.io/v1",
          "kind": "ManifestWork",
          "metadata": {
                "name": "mw",
                "namespace": "cluster1"
          },
          "spec": {
                "workload": { "manifests": [
                        {
                          "apiVersion": "v1",
                          "data": {
                                "mambo": "poa"
                          },
                          "kind": "Secret",
                          "metadata": {
                                "name": "test",
                                "namespace": "test"
                          }
                        }
                  ]}
          }
        }
  }
EOF
```

2. Delete the resource using the id given after the create call; replace the `<resource_id>` below with the id returned from 1
```
ocm delete /api/maestro/v1/resources/<resource_id>
```
3. Once the resource is successful deleted, attempt to recreate it again using step (1) above. And observe the failure.

A quick debug reveals this to be a DB level constraint of uniqueness name and soft deletion.
Since the resource in step(2) is soft deleted, it's still present in the database. Recreating a resource with the same name afterwards fail since the resource still exists in the DB. 

The constraint is defined as 
```
 "idx_resources_name" UNIQUE, btree (name)
```

**Comment by clyang82** [comment]
Do you have agent available? the agent should report back the deletion status and then we will delete from DB. We may introduce force deletion after 5 mins.

**Comment by machi1990** [comment]
> the agent should report back the deletion status and then we will delete from DB

@clyang82 Hey, Yes. The agent is available. I confirm that deleted resource was marked for deletion successfully and then soft deleted. The issue is that once it was soft deleted, it remained in the database making it impossible to create another resource with the same name.

**Comment by clyang82** [comment]
@machi1990 this issue was fixed. please verify it. Thanks.

**Comment by machi1990** [comment]
Thank you. I've verified the code change. It looks good to me. I'll close the issue.
