### ISSUE TITLE
Allow to list the Bundle resources by RESTful API

### ISSUE THREAD

**Issue by skeeey** [openshift-online/maestro#103]
Allow to list the resource of type Bundle by RESTful API, then we can use this API to initialize the ManifestWork source client cache with this API, this will have two related tasks

- [x] Add a RESTful API to list `Bundle` resources
- [x] Enhance sdk-go to support initialize the ManifestWork source client cache  with a customized list function (https://github.com/open-cluster-management-io/ocm/issues/476)
- [ ] ~Provide a list function in maestro that list `Bundle` resources with the RESTful API and wrap the maestro resource to ManifestWork, then user can use this list function to build their ManifestWork source client~ (use #104 instead)

refer to https://github.com/open-cluster-management-io/ocm/issues/483

**Comment by morvencao** [comment]
need to update openAPI schema for this.
current list API return a list of 'Resource',
we should return a list of 'ManifestBundle' for this new requirement.

**Comment by clyang82** [comment]
How about the name for API`/api/maestro/v1/resource-bundles` for all ManifestBundle resources?
`Post /api/maestro/v1/resource-bundles`
`GET/PATCH/DELETE /api/maestro/v1/resource-bundles/${bundle_id}`

**Comment by morvencao** [comment]
we don't need POST, PATCH and DELETE, right? only need GET and LIST?

**Comment by skeeey** [comment]
For POST, PATCH and DELETE, we may still to use grpc publish method to do them

**Comment by morvencao** [comment]
drafted a PR for this: https://github.com/openshift-online/maestro/pull/106

**Comment by clyang82** [comment]
@machi1990 the resource-bundles api is also ready for your use. please verify it as well. Thanks.
