### ISSUE TITLE
Allow multiple grpc source clients to CRUD resources to maestro and only one source client watches the resource  at the same time

### ISSUE THREAD

**Issue by skeeey** [openshift-online/maestro#104]
For this issue, we may need to build a new grpc source manifestwork client without local cache, the related tasks

- [x] the new grpc source manifestwork client get/list the bundle resources by maestro RESTful APIs (https://github.com/openshift-online/maestro/pull/122)
- [x] the new grpc source manifestwork client create/update/delete the bundle resource by publish method provided by the maestro grpc service (https://github.com/openshift-online/maestro/pull/122)
- [x] the new grpc source manifestwork client watch the bundle resource status by grpc subscribe method provided by the maestro grpc service (https://github.com/openshift-online/maestro/pull/122)
- [x] enhance the the manifestwork status payload  to save manifestwork spec in sdk-go, and the maestro server sends the manifestwork status with manifestwork spec to the source client, thus the user can get a whole manifestwork by source manifestwork client watch (https://github.com/open-cluster-management-io/sdk-go/pull/55)

refer to https://github.com/open-cluster-management-io/ocm/issues/483

**Comment by machi1990** [comment]
Thanks for opening this, I am super excited by having this. Am I to understand correctly that this new client won't depend on a Lister?

**Comment by skeeey** [comment]
yes, it will not need. a local Lister

**Comment by machi1990** [comment]
👍 Perfect and thanks for the clarification.

**Comment by machi1990** [comment]
Thank you @skeeey 

I've tested the flow;

The ops CREATE,GET,LIST,DELETE,PATCH, WATCH all works.

I also tested full resync using `.WithResyncEnabled(true)` and I saw two different behaviour;
- Initially, I was not getting the full resync.
- When I update my maestro deployment, I started getting the full resync on client restart. 

```shell
 go run cmd/example/watcher/main.go                                                                                        [12:25:48]
{"level":"info","ts":1718360752.690721,"logger":"fallback","caller":"protocol/protocol.go:112","msg":"subscribing events for: cs-example"}
{"level":"info","ts":1718360752.713562,"logger":"fallback","caller":"protocol/protocol.go:82","msg":"publishing event with id: 959ce9b3-2bce-4426-92ae-b58ce253ebb1"}
status update: %v 98ba1846-89d9-5e47-8ac8-c3f584cec1f9
status update: %v 07372a51-5077-5b68-9cac-ab695a952abe
```

I do not know what can account for this behaviour change, but as discussed in DM, It's desirable for full resync to be made resilient and reliable on client restart/reconnection. I'll be happy to review work on this area.

**Comment by machi1990** [comment]
I've created a separate issue on that https://github.com/openshift-online/maestro/issues/131
