### ISSUE TITLE
Introduce "external_id"

### ISSUE THREAD

**Issue by clyang82** [openshift-online/maestro#67]
if you post the same resource, i believe you'd get dupes.   Maestro isn't inspecting the generic payload.  not sure this is even practical.
it might be best, then, to include an "external_id" that CS can provide (its own PK for that record, for example) that is unique.
in this way:
TX1: CS persists to db, gets a PK
TX2: CS posts resource w/ the PK.   it would fail if the same resource is posted more than once.
TX3: Maestro can have many copies of this resource in the queue.  resources are applied idempotently in the cluster.

FYI @markturansky

**Comment by clyang82** [comment]
working on this issue.

**Comment by markturansky** [comment]
@clyang82 is this a moot point now that `name` is provided by the caller and enforced for uniqueness?

**Comment by markturansky** [comment]
see https://github.com/openshift-online/maestro/pull/63

**Comment by clyang82** [comment]
Yes. I think it can be. if the name is provided, then we use it and enforce for uniqueness. if the name is not provided, then we use ID as the name.
