### ISSUE TITLE
Allow user to set resources' source when creating a resource via the rest API

### ISSUE THREAD

**Issue by machi1990** [openshift-online/maestro#97]
At the moment it is not possible to set the `source` when creating a resource via a restful API.
This makes watching the resources created via the rest API impossible.

@qiujian16 @clyang82 following discussions we've two options:

1. setting the source as maestro by default
2. allow user to specify the resource's source

**Comment by clyang82** [comment]
Yes. You are right. You can get resource by using `ocm get /api/maestro/v1/resources -p search="source = 'maestro'"`

**Comment by clyang82** [comment]
@machi1990 are you fine with the default source as maestro? if so, the PR was merged. Please give a try and then close this issue. Thanks.

**Comment by machi1990** [comment]
Thanks for this.
